AUDIO_ENABLE = no
SPLIT_KEYBOARD = yes
SPLIT_USB_DETECT = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
RGB_MATRIX_SERIAL_DRIVER = yes
RGB_MATRIX_SPLIT_USB_DRIVER = yes # Si vous utilisez un câble TRRS pour connecter les deux moitiés
WS2812_DRIVER_REQUIRED = yes